### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by nekr0z** [willnorris/webmention#19] opened 2022-01-08 14:54 UTC
Sending a webmention from https://evgenykuznetsov.org/en/reactions/2022/re-008143650/ to https://jamesg.blog/2022/01/06/brainstorming-email-to-rss/:

```
Select links to send webmentions to:
  [ ]:  0. https://evgenykuznetsov.org
  [ ]:  1. https://evgenykuznetsov.org/en/reactions/2022/re-008143650/
  [ ]:  2. https://fed.brid.gy/
  [ ]:  3. https://brid.gy/publish/twitter
  [x]:  4. https://jamesg.blog/2022/01/06/brainstorming-email-to-rss/
  [ ]:  5. javascript:void(0);
  [ ]:  6. https://evgenykuznetsov.org/en/
  [ ]:  7. https://evgenykuznetsov.org/en/reactions/2022/re-008143650/comments.xml
  [ ]:  8. https://evgenykuznetsov.org/en/webmentions

Enter space separated IDs of links to toggle, [a]ll or [n]one: 

Sending webmentions...
  https://jamesg.blog/2022/01/06/brainstorming-email-to-rss/ ... panic: runtime error: slice bounds out of range [62:61]

goroutine 1 [running]:
willnorris.com/go/webmention/third_party/header.expectLinkValue(0xc00023e300, 0x3d, 0xc00023e2f0, 0x0, 0x0, 0x0)
        /home/evgeny/go/src/willnorris.com/go/webmention/third_party/header/header.go:175 +0xbe
willnorris.com/go/webmention/third_party/header.ParseLink(0xc00023e300, 0x3d, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/evgeny/go/src/willnorris.com/go/webmention/third_party/header/header.go:117 +0x5e
willnorris.com/go/webmention.httpLink(0xc000706270, 0x0, 0x0)
        /home/evgeny/go/src/willnorris.com/go/webmention/http.go:19 +0x116
willnorris.com/go/webmention.extractEndpoint(0xc000174120, 0xc000620300, 0x3a, 0xc000174120, 0x0)
        /home/evgeny/go/src/willnorris.com/go/webmention/webmention.go:84 +0x33
willnorris.com/go/webmention.(*Client).DiscoverEndpoint(0xc000010028, 0xc000620300, 0x3a, 0x0, 0x0, 0x0, 0x0)
        /home/evgeny/go/src/willnorris.com/go/webmention/webmention.go:66 +0x16d
main.sendWebmentions(0xc000602300, 0x9, 0x10)
        /home/evgeny/go/src/willnorris.com/go/webmention/cmd/webmention/main.go:127 +0x186
main.main()
        /home/evgeny/go/src/willnorris.com/go/webmention/cmd/webmention/main.go:70 +0x2ec
```

**Comment by willnorris** [comment] 2022-01-08 17:09
So I can reproduce this, and I think it's due to a malformed HTTP header in the response from jamesg.blog:

``` sh
% curl -I https://jamesg.blog/2022/01/06/brainstorming-email-to-rss/
HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Sat, 08 Jan 2022 17:05:23 GMT
Content-Type: text/html
Content-Length: 15368
Last-Modified: Sat, 08 Jan 2022 14:22:25 GMT
Connection: keep-alive
ETag: "61d99e21-3c08"
link: <https://micropub.jamesg.blog/micropub>; rel='micropub'
link: <https://microsub.jamesg.blog/endpoint>; rel='microsub'
link: <https://webmention.jamesg.blog/endpoint>; rel='webmention'
link: <https://auth.jamesg.blog/auth>; rel='authorization_endpoint'
link: <https://auth.jamesg.blog/token>; rel='token_endpoint'
link: <https://webmention.io/jamesg.blog/xmlrpc>; rel='pingback'
link: <https://microsub.jamesg.blog/discover-feed?; rel='subscribe'
Accept-Ranges: bytes
```

The last `link` header, `link: <https://microsub.jamesg.blog/discover-feed?; rel='subscribe'` doesn't have a closing angle bracket around the URL, `>`.  Looking at the stack trace, that's almost certainly the issue.  However, the library shouldn't crash on a malformed header... instead, it should just skip it.

I've never loved the fact that I was vendoring the link parsing code from gddo, especially now that that code is long abandoned.  This might be a good opportunity to find a proper HTTP link parsing library to use.

**Comment by nekr0z** [comment] 2022-01-08 17:53
> doesn't have a closing angle bracket around the URL, `>`

Good catch! Tagging @capjamesg here to let him know.


> the library shouldn't crash on a malformed header.

Absolutely!

I'll have a look at the code in question as soon as I have time. Should be easily fixable; parsing HTTP headers is no rocket science, shouldn't really need a whole separate library for that IMO.

**Comment by willnorris** [comment] 2022-01-08 18:17
> parsing HTTP headers is no rocket science, shouldn't really need a whole separate library for that IMO

oh, it's certainly not hard.  But it feels like the kind of very generic functionality that shouldn't need to be reimplemented in every project that needs to deal with link headers.  It's the kind of thing that ought to be in https://pkg.go.dev/golang.org/x/net/http/httpguts or a similar package.

**Comment by capjamesg** [comment] 2022-01-08 18:17
Thank you for pointing out the malformed header. The question mark should have been a closing angle bracket. I apologise that this caused an error. Definitely an issue on my part. I have just pushed a fix. Do let me know if you encounter any other issues.

**Closed** 2022-01-08 18:32 UTC

**Comment by nekr0z** [comment] 2022-01-08 19:58
@capjamesg thank _you_ for helping discover a bug!
